lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: openintegrity.org
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
front:
  scale: 1
api:
  scale: 1
email:
  scale: 1
